"""Shared infrastructure used by layers layers."""

from .base import PhysicalLayerBase, SoenLayerBase, VirtualLayerBase
from .connectivity import (
    ConnectivityModule,
    apply_connectivity,
    resolve_connectivity_matrix,
)
from .connectivity_builders import (
    CONNECTIVITY_BUILDERS,
    build_all_to_all,
    build_chain,
    build_connectivity,
    build_constant,
    build_custom,
    build_dense,
    build_exponential,
    build_one_to_one,
    build_power_law,
    build_sparse,
)
from .connectivity_metadata import (
    CONNECTIVITY_DESCRIPTIONS,
    CONNECTIVITY_PARAM_TYPES,
    WEIGHT_INITIALIZER_DESCRIPTIONS,
    WEIGHT_INITIALIZER_PARAM_TYPES,
    WEIGHT_INITIALIZERS,
    build_weight,
    remove_self_connections,
)
from .features import (
    CompositeFeature,
    FeatureContext,
    FeatureHook,
    HistoryTrackingFeature,
    NoiseFeature,
    PowerStorage,
    PowerTrackingFeature,
    QuantizationFeature,
    StepPayload,
)
from .metadata import (
    INIT_METHOD_PARAMS,
    INIT_OPTIONAL_PARAMS,
    LAYER_PARAM_CONFIGS,
    ParamConfig,
    apply_param_constraints,
    create_layer_parameters,
    initialize_values_deterministic,
    initialize_values_stochastic,
    noise_keys_for_layer,
    parse_param_config,
)
from .parameters import Constraint, InitializerSpec, ParameterDef, ParameterRegistry
from .solvers import (
    CoefficientProvider,
    ForwardEulerSolver,
    ParallelScanSolver,
    ParaRNNSolver,
    SolverBase,
    StepProvider,
)
from .validators import broadcast_initial_state, validate_sequence_input

__all__ = [
    "CONNECTIVITY_BUILDERS",
    "CONNECTIVITY_DESCRIPTIONS",
    "CONNECTIVITY_PARAM_TYPES",
    "INIT_METHOD_PARAMS",
    "INIT_OPTIONAL_PARAMS",
    "LAYER_PARAM_CONFIGS",
    "WEIGHT_INITIALIZERS",
    "WEIGHT_INITIALIZER_DESCRIPTIONS",
    "WEIGHT_INITIALIZER_PARAM_TYPES",
    "CoefficientProvider",
    "CompositeFeature",
    "ConnectivityModule",
    "Constraint",
    "FeatureContext",
    "FeatureHook",
    "ForwardEulerSolver",
    "HistoryTrackingFeature",
    "InitializerSpec",
    "NoiseFeature",
    "ParallelScanSolver",
    "ParaRNNSolver",
    "ParamConfig",
    "ParameterDef",
    "ParameterRegistry",
    "PhysicalLayerBase",
    "PowerStorage",
    "PowerTrackingFeature",
    "QuantizationFeature",
    "SoenLayerBase",
    "SolverBase",
    "StepPayload",
    "StepProvider",
    "VirtualLayerBase",
    "apply_connectivity",
    "apply_param_constraints",
    "broadcast_initial_state",
    "build_all_to_all",
    "build_chain",
    "build_connectivity",
    "build_constant",
    "build_custom",
    "build_dense",
    "build_exponential",
    "build_one_to_one",
    "build_power_law",
    "build_sparse",
    "build_weight",
    "create_layer_parameters",
    "initialize_values_deterministic",
    "initialize_values_stochastic",
    "noise_keys_for_layer",
    "parse_param_config",
    "remove_self_connections",
    "resolve_connectivity_matrix",
    "validate_sequence_input",
]
